<?php

namespace Database\Seeders;

use App\Models\Blog;
use App\Models\News;
use App\Models\Property;
use App\Models\Testimonial;
use App\Models\User;
use App\Models\Company;
use App\Models\Team;
use App\Models\TeamMember;
use App\Models\BrokerPlan;
use App\Models\BrokerSubscription;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Create admin account
        $admin = User::where('email', 'admin@rentals.ph')->first();
        if (!$admin) {
            User::create([
                'first_name' => 'Admin',
                'last_name' => 'User',
                'email' => 'admin@rentals.ph',
                'password' => Hash::make('admin'),
                'role' => 'admin',
                'verified' => true,
                'is_active' => true,
                'email_verified_at' => now(),
            ]);
        } else {
            // Update existing admin to ensure password is correct
            $admin->password = Hash::make('admin');
            $admin->role = 'admin';
            $admin->verified = true;
            $admin->is_active = true;
            $admin->save();
        }

        // Create multiple agents (formerly rent managers)
        $agents = [
            User::firstOrCreate(
                ['email' => 'official@rentals.ph'],
                [
                    'first_name' => 'RentalPh',
                    'last_name' => 'Official',
                    'password' => Hash::make('password'),
                    'role' => 'agent',
                    'verified' => true,
                    'is_active' => true,
                    'status' => 'approved',
                    'email_verified_at' => now(),
                    'image_path' => 'images/users/1/avatar.jpg',
                    'city' => 'Cebu City',
                    'state' => 'Cebu',
                    'phone' => '+63 32 123 4567',
                    'agency_name' => 'Rentals.ph Official',
                    'license_type' => 'broker',
                    'prc_license_number' => 'PRC-001',
                ]
            ),
            User::firstOrCreate(
                ['email' => 'glaiza.jerome@rentals.ph'],
                [
                    'first_name' => 'Glaiza',
                    'last_name' => 'Lantaca',
                    'password' => Hash::make('password'),
                    'role' => 'agent',
                    'verified' => true,
                    'is_active' => true,
                    'status' => 'approved',
                    'email_verified_at' => now(),
                    'image_path' => 'images/users/2/avatar.jpg',
                    'city' => 'Cebu City',
                    'state' => 'Cebu',
                    'phone' => '+63 917 123 4567',
                    'agency_name' => 'Premium Realty',
                    'license_type' => 'broker',
                    'prc_license_number' => 'PRC-002',
                ]
            ),
            User::firstOrCreate(
                ['email' => 'miguel.abella@rentals.ph'],
                [
                    'first_name' => 'Miguel',
                    'last_name' => 'Abella',
                    'password' => Hash::make('password'),
                    'role' => 'agent',
                    'verified' => true,
                    'is_active' => true,
                    'status' => 'approved',
                    'email_verified_at' => now(),
                    'image_path' => 'images/users/3/avatar.jpg',
                    'city' => 'Cebu City',
                    'state' => 'Cebu',
                    'phone' => '+63 917 234 5678',
                    'agency_name' => 'Elite Properties',
                    'license_type' => 'salesperson',
                    'prc_license_number' => 'PRC-003',
                ]
            ),
            User::firstOrCreate(
                ['email' => 'maria.santos@rentals.ph'],
                [
                    'first_name' => 'Maria',
                    'last_name' => 'Santos',
                    'password' => Hash::make('password'),
                    'role' => 'agent',
                    'verified' => true,
                    'is_active' => true,
                    'status' => 'approved',
                    'email_verified_at' => now(),
                    'image_path' => 'images/users/4/avatar.jpg',
                    'city' => 'Cebu City',
                    'state' => 'Cebu',
                    'phone' => '+63 917 345 6789',
                    'agency_name' => 'Metro Realty Group',
                    'license_type' => 'broker',
                    'prc_license_number' => 'PRC-004',
                ]
            ),
            User::firstOrCreate(
                ['email' => 'john.reyes@rentals.ph'],
                [
                    'first_name' => 'John',
                    'last_name' => 'Reyes',
                    'password' => Hash::make('password'),
                    'role' => 'agent',
                    'verified' => true,
                    'is_active' => true,
                    'status' => 'approved',
                    'email_verified_at' => now(),
                    'image_path' => 'images/users/5/avatar.jpg',
                    'city' => 'Cebu City',
                    'state' => 'Cebu',
                    'phone' => '+63 917 456 7890',
                    'agency_name' => 'City Properties',
                    'license_type' => 'salesperson',
                    'prc_license_number' => 'PRC-005',
                ]
            ),
            User::firstOrCreate(
                ['email' => 'catherine.lim@rentals.ph'],
                [
                    'first_name' => 'Catherine',
                    'last_name' => 'Lim',
                    'password' => Hash::make('password'),
                    'role' => 'agent',
                    'verified' => true,
                    'is_active' => true,
                    'status' => 'approved',
                    'email_verified_at' => now(),
                    'image_path' => 'images/users/6/avatar.jpg',
                    'city' => 'Cebu City',
                    'state' => 'Cebu',
                    'phone' => '+63 917 567 8901',
                    'agency_name' => 'Luxury Homes',
                    'license_type' => 'broker',
                    'prc_license_number' => 'PRC-006',
                ]
            ),
            User::firstOrCreate(
                ['email' => 'roberto.cruz@rentals.ph'],
                [
                    'first_name' => 'Roberto',
                    'last_name' => 'Cruz',
                    'password' => Hash::make('password'),
                    'role' => 'agent',
                    'verified' => true,
                    'is_active' => true,
                    'status' => 'approved',
                    'email_verified_at' => now(),
                    'image_path' => 'images/users/7/avatar.jpg',
                    'city' => 'Cebu City',
                    'state' => 'Cebu',
                    'phone' => '+63 917 678 9012',
                    'agency_name' => 'Prime Real Estate',
                    'license_type' => 'salesperson',
                    'prc_license_number' => 'PRC-007',
                ]
            ),
            User::firstOrCreate(
                ['email' => 'angela.fernandez@rentals.ph'],
                [
                    'first_name' => 'Angela',
                    'last_name' => 'Fernandez',
                    'password' => Hash::make('password'),
                    'role' => 'agent',
                    'verified' => true,
                    'is_active' => true,
                    'status' => 'approved',
                    'email_verified_at' => now(),
                    'image_path' => 'images/users/8/avatar.jpg',
                    'city' => 'Cebu City',
                    'state' => 'Cebu',
                    'phone' => '+63 917 789 0123',
                    'agency_name' => 'Dream Properties',
                    'license_type' => 'broker',
                    'prc_license_number' => 'PRC-008',
                ]
            ),
            User::firstOrCreate(
                ['email' => 'james.wilson@rentals.ph'],
                [
                    'first_name' => 'James',
                    'last_name' => 'Wilson',
                    'password' => Hash::make('password'),
                    'role' => 'agent',
                    'verified' => true,
                    'is_active' => true,
                    'status' => 'approved',
                    'email_verified_at' => now(),
                    'image_path' => 'images/users/9/avatar.jpg',
                    'city' => 'Cebu City',
                    'state' => 'Cebu',
                    'phone' => '+63 917 890 1234',
                    'agency_name' => 'Global Realty',
                    'license_type' => 'salesperson',
                    'prc_license_number' => 'PRC-009',
                ]
            ),
        ];

        // Update agents to ensure they have profile pictures and other fields
        $agentUpdates = [
            ['email' => 'official@rentals.ph', 'image_path' => 'images/users/1/avatar.jpg', 'city' => 'Cebu City', 'state' => 'Cebu', 'phone' => '+63 32 123 4567', 'agency_name' => 'Rentals.ph Official', 'license_type' => 'broker', 'prc_license_number' => 'PRC-001'],
            ['email' => 'glaiza.jerome@rentals.ph', 'image_path' => 'images/users/2/avatar.jpg', 'city' => 'Cebu City', 'state' => 'Cebu', 'phone' => '+63 917 123 4567', 'agency_name' => 'Premium Realty', 'license_type' => 'broker', 'prc_license_number' => 'PRC-002'],
            ['email' => 'miguel.abella@rentals.ph', 'image_path' => 'images/users/3/avatar.jpg', 'city' => 'Cebu City', 'state' => 'Cebu', 'phone' => '+63 917 234 5678', 'agency_name' => 'Elite Properties', 'license_type' => 'salesperson', 'prc_license_number' => 'PRC-003'],
            ['email' => 'maria.santos@rentals.ph', 'image_path' => 'images/users/4/avatar.jpg', 'city' => 'Cebu City', 'state' => 'Cebu', 'phone' => '+63 917 345 6789', 'agency_name' => 'Metro Realty Group', 'license_type' => 'broker', 'prc_license_number' => 'PRC-004'],
            ['email' => 'john.reyes@rentals.ph', 'image_path' => 'images/users/5/avatar.jpg', 'city' => 'Cebu City', 'state' => 'Cebu', 'phone' => '+63 917 456 7890', 'agency_name' => 'City Properties', 'license_type' => 'salesperson', 'prc_license_number' => 'PRC-005'],
            ['email' => 'catherine.lim@rentals.ph', 'image_path' => 'images/users/6/avatar.jpg', 'city' => 'Cebu City', 'state' => 'Cebu', 'phone' => '+63 917 567 8901', 'agency_name' => 'Luxury Homes', 'license_type' => 'broker', 'prc_license_number' => 'PRC-006'],
            ['email' => 'roberto.cruz@rentals.ph', 'image_path' => 'images/users/7/avatar.jpg', 'city' => 'Cebu City', 'state' => 'Cebu', 'phone' => '+63 917 678 9012', 'agency_name' => 'Prime Real Estate', 'license_type' => 'salesperson', 'prc_license_number' => 'PRC-007'],
            ['email' => 'angela.fernandez@rentals.ph', 'image_path' => 'images/users/8/avatar.jpg', 'city' => 'Cebu City', 'state' => 'Cebu', 'phone' => '+63 917 789 0123', 'agency_name' => 'Dream Properties', 'license_type' => 'broker', 'prc_license_number' => 'PRC-008'],
            ['email' => 'james.wilson@rentals.ph', 'image_path' => 'images/users/9/avatar.jpg', 'city' => 'Cebu City', 'state' => 'Cebu', 'phone' => '+63 917 890 1234', 'agency_name' => 'Global Realty', 'license_type' => 'salesperson', 'prc_license_number' => 'PRC-009'],
        ];

        foreach ($agentUpdates as $update) {
            $email = $update['email'];
            unset($update['email']);
            User::where('email', $email)->update($update);
        }

        // Create broker account
        $broker = User::where('email', 'broker@rentals.ph')->first();
        if (!$broker) {
            $broker = User::create([
                'first_name' => 'John',
                'last_name' => 'Broker',
                'email' => 'broker@rentals.ph',
                'password' => Hash::make('password'),
                'role' => 'broker',
                'verified' => true,
                'is_active' => true,
                'phone' => '+63 912 345 6789',
                'email_verified_at' => now(),
            ]);
        } else {
            // Update existing broker to ensure password is correct
            $broker->password = Hash::make('password');
            $broker->role = 'broker';
            $broker->verified = true;
            $broker->is_active = true;
            $broker->save();
        }

        // Get or create a broker plan (use default Credit Plan)
        $brokerPlan = BrokerPlan::where('name', 'Credit Plan')->first();
        if (!$brokerPlan) {
            $brokerPlan = BrokerPlan::create([
                'name' => 'Credit Plan',
                'description' => 'Default credit plan with 10 listings, 5 teams, and 10 agents',
                'max_listings' => 10,
                'max_teams' => 5,
                'max_agents' => 10,
                'price' => 0,
                'billing_period' => 'monthly',
                'is_active' => true,
            ]);
        }

        // Create broker subscription
        $subscription = BrokerSubscription::where('broker_id', $broker->id)
            ->where('status', 'active')
            ->first();
        if (!$subscription) {
            $subscription = BrokerSubscription::create([
                'broker_id' => $broker->id,
                'plan_id' => $brokerPlan->id,
                'listings_used' => 0,
                'teams_used' => 0,
                'agents_used' => 0,
                'status' => 'active',
                'starts_at' => now(),
                'expires_at' => now()->addMonth(),
            ]);
        }

        // Create a company for the broker
        $company = Company::where('broker_id', $broker->id)->first();
        if (!$company) {
            $company = Company::create([
                'broker_id' => $broker->id,
                'name' => 'Premium Realty Group',
                'description' => 'Leading real estate brokerage firm specializing in luxury properties',
                'address' => '123 Business District, Makati City',
                'phone' => '+63 2 8888 9999',
                'email' => 'info@premiumrealty.ph',
                'website' => 'https://premiumrealty.ph',
                'is_active' => true,
            ]);
        }

        // Create a team for the broker
        $team = Team::where('broker_id', $broker->id)->first();
        if (!$team) {
            $team = Team::create([
                'broker_id' => $broker->id,
                'company_id' => $company->id,
                'name' => 'Sales Team Alpha',
                'description' => 'Top performing sales team specializing in residential properties',
                'is_active' => true,
            ]);
        }

        // Assign some agents to the broker's team (first 3 agents)
        if ($agents && count($agents) >= 3) {
            foreach (array_slice($agents, 0, 3) as $agent) {
                $teamMember = TeamMember::where('team_id', $team->id)
                    ->where('agent_id', $agent->id)
                    ->first();
                if (!$teamMember) {
                    TeamMember::create([
                        'team_id' => $team->id,
                        'agent_id' => $agent->id,
                        'role' => 'member',
                        'is_active' => true,
                        'joined_at' => now(),
                    ]);
                }
            }
        }

        // Update subscription usage counters to reflect actual usage
        if ($subscription) {
            $subscription->update([
                'teams_used' => Team::where('broker_id', $broker->id)->count(),
                'agents_used' => TeamMember::whereHas('team', function($query) use ($broker) {
                    $query->where('broker_id', $broker->id);
                })->count(),
            ]);
        }

        // Properties - distributed evenly across all agents (All in Cebu City)
        // Ensure all properties have agent_id assigned to one of the seeded agents
        $properties = [
            [
                'title' => 'Azure Residences - 2BR Corner Suite',
                'description' => 'Beautiful corner suite with modern amenities, floor-to-ceiling windows, and stunning city views. Located in the heart of IT Park with easy access to shopping, dining, and transportation.',
                'type' => 'Apartment / Condo',
                'price' => 25000,
                'price_type' => 'Monthly',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'garage' => 1,
                'area' => 65,
                'lot_area' => 65,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Swimming Pool', 'Gym', 'Parking', 'Security', 'Elevator'],
                'furnishing' => 'Fully Furnished',
                'image' => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Salinas Drive, Lahug',
                'latitude' => '10.3231',
                'longitude' => '123.9062',
                'is_featured' => true,
                'agent_id' => $agents[0]->id,
                'published_at' => now(),
            ],
            [
                'title' => 'Modern 3BR Condo in IT Park',
                'description' => 'Spacious 3-bedroom condominium in Cebu IT Park. Features modern design, fully furnished, with access to world-class amenities including pool, gym, and 24/7 security.',
                'type' => 'Apartment / Condo',
                'price' => 35000,
                'price_type' => 'Monthly',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'garage' => 1,
                'area' => 85,
                'lot_area' => 85,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Swimming Pool', 'Gym', 'Rooftop Garden', 'Function Room', 'Parking', 'Security'],
                'furnishing' => 'Fully Furnished',
                'image' => 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Pope John Paul II Avenue, Cebu IT Park',
                'latitude' => '10.3200',
                'longitude' => '123.9050',
                'is_featured' => true,
                'agent_id' => $agents[0]->id,
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Cozy 2BR Apartment in Ayala Center',
                'description' => 'Charming 2-bedroom apartment near Ayala Center Cebu. Perfect for young professionals or couples. Walking distance to offices, malls, and restaurants.',
                'type' => 'Apartment / Condo',
                'price' => 22000,
                'price_type' => 'Monthly',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'garage' => 0,
                'area' => 55,
                'lot_area' => 55,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Security', 'Elevator'],
                'furnishing' => 'Semi Furnished',
                'image' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Cardinal Rosales Avenue, Cebu Business Park',
                'latitude' => '10.3157',
                'longitude' => '123.8854',
                'is_featured' => false,
                'agent_id' => $agents[1]->id,
                'published_at' => now()->subDays(5),
            ],
            [
                'title' => 'Luxury 4BR House in Banilad',
                'description' => 'Stunning 4-bedroom house with garden and pool. Perfect for families seeking comfort and luxury. Located in a quiet, gated community in Banilad with excellent security.',
                'type' => 'House',
                'price' => 65000,
                'price_type' => 'Monthly',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'garage' => 3,
                'area' => 250,
                'lot_area' => 400,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Swimming Pool', 'Garden', 'Parking', 'Security', 'Maid\'s Room'],
                'furnishing' => 'Fully Furnished',
                'image' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Banilad Road, Banilad',
                'latitude' => '10.3392',
                'longitude' => '123.8944',
                'is_featured' => true,
                'agent_id' => $agents[1]->id,
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'Studio Unit in Lahug',
                'description' => 'Compact and efficient studio unit ideal for single professionals. Located in Lahug with easy access to IT Park, shopping malls, and public transport.',
                'type' => 'Studio',
                'price' => 15000,
                'price_type' => 'Monthly',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'garage' => 0,
                'area' => 28,
                'lot_area' => 28,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Gym', 'Swimming Pool', 'Security', 'Elevator'],
                'furnishing' => 'Fully Furnished',
                'image' => 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Gorordo Avenue, Lahug',
                'latitude' => '10.3300',
                'longitude' => '123.9000',
                'is_featured' => false,
                'agent_id' => $agents[2]->id,
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Retail Space in Colon Street',
                'description' => 'Prime retail space in a high-traffic area of Colon Street. Perfect for restaurants, cafes, or retail businesses. High visibility and excellent foot traffic.',
                'type' => 'Commercial',
                'price' => 45000,
                'price_type' => 'Monthly',
                'bedrooms' => 0,
                'bathrooms' => 2,
                'garage' => 0,
                'area' => 150,
                'lot_area' => 150,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Parking', 'Security', 'Air Conditioning'],
                'furnishing' => 'Unfurnished',
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Colon Street, Downtown Cebu',
                'latitude' => '10.2950',
                'longitude' => '123.9014',
                'is_featured' => false,
                'agent_id' => $agents[2]->id,
                'published_at' => now()->subDays(4),
            ],
            [
                'title' => 'Family-Friendly 3BR Townhouse in Talamban',
                'description' => 'Comfortable 3-bedroom townhouse in a family-oriented community. Features a small garden, parking space, and is close to schools and markets.',
                'type' => 'Townhouse',
                'price' => 28000,
                'price_type' => 'Monthly',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'garage' => 2,
                'area' => 120,
                'lot_area' => 180,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Garden', 'Parking', 'Security'],
                'furnishing' => 'Semi Furnished',
                'image' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Talamban Road, Talamban',
                'latitude' => '10.3800',
                'longitude' => '123.9200',
                'is_featured' => false,
                'agent_id' => $agents[3]->id,
                'published_at' => now()->subDays(6),
            ],
            [
                'title' => 'Executive 1BR Condo in Cebu Business Park',
                'description' => 'Premium 1-bedroom condominium in Cebu Business Park. Perfect for executives. Features modern finishes, high-speed internet ready, and concierge services.',
                'type' => 'Apartment / Condo',
                'price' => 28000,
                'price_type' => 'Monthly',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'garage' => 1,
                'area' => 45,
                'lot_area' => 45,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Swimming Pool', 'Gym', 'Concierge', 'Business Center', 'Parking', 'Security'],
                'furnishing' => 'Fully Furnished',
                'image' => 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Cardinal Rosales Avenue, Cebu Business Park',
                'latitude' => '10.3157',
                'longitude' => '123.8854',
                'is_featured' => true,
                'agent_id' => $agents[3]->id,
                'published_at' => now()->subDays(7),
            ],
            [
                'title' => 'Spacious 5BR House with Pool in Capitol Site',
                'description' => 'Large 5-bedroom family house with private pool and extensive garden. Ideal for large families or those who love to entertain. Located in a prestigious subdivision in Capitol Site.',
                'type' => 'House',
                'price' => 75000,
                'price_type' => 'Monthly',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'garage' => 4,
                'area' => 350,
                'lot_area' => 600,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Swimming Pool', 'Garden', 'Gazebo', 'Parking', 'Security', 'Maid\'s Quarters'],
                'furnishing' => 'Fully Furnished',
                'image' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Escario Street, Capitol Site',
                'latitude' => '10.3100',
                'longitude' => '123.8900',
                'is_featured' => true,
                'agent_id' => $agents[4]->id,
                'published_at' => now()->subDays(8),
            ],
            [
                'title' => 'Budget-Friendly 1BR Apartment near USC',
                'description' => 'Affordable 1-bedroom apartment perfect for students or young professionals. Clean, well-maintained, and located near University of San Carlos and public transportation.',
                'type' => 'Apartment / Condo',
                'price' => 10000,
                'price_type' => 'Monthly',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'garage' => 0,
                'area' => 35,
                'lot_area' => 35,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Security'],
                'furnishing' => 'Unfurnished',
                'image' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'P. del Rosario Street, Downtown Cebu',
                'latitude' => '10.3000',
                'longitude' => '123.9000',
                'is_featured' => false,
                'agent_id' => $agents[4]->id,
                'published_at' => now()->subDays(9),
            ],
            [
                'title' => 'Office Space in IT Park',
                'description' => 'Modern office space available for lease in Cebu IT Park. Ideal for startups or small businesses. Features meeting rooms, reception area, and high-speed internet connectivity.',
                'type' => 'Office',
                'price' => 40000,
                'price_type' => 'Monthly',
                'bedrooms' => 0,
                'bathrooms' => 3,
                'garage' => 5,
                'area' => 200,
                'lot_area' => 200,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Parking', 'Security', 'Air Conditioning', 'Meeting Rooms', 'Reception Area'],
                'furnishing' => 'Semi Furnished',
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Pope John Paul II Avenue, Cebu IT Park',
                'latitude' => '10.3200',
                'longitude' => '123.9050',
                'is_featured' => false,
                'agent_id' => $agents[5]->id,
                'published_at' => now()->subDays(10),
            ],
            [
                'title' => 'Penthouse 2BR in IT Park',
                'description' => 'Exclusive penthouse unit with panoramic city views. Features premium finishes, private balcony, and access to luxury amenities. Perfect for discerning tenants.',
                'type' => 'Apartment / Condo',
                'price' => 85000,
                'price_type' => 'Monthly',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'garage' => 2,
                'area' => 110,
                'lot_area' => 110,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Swimming Pool', 'Gym', 'Rooftop Lounge', 'Concierge', 'Valet Parking', 'Security', 'Private Balcony'],
                'furnishing' => 'Fully Furnished',
                'image' => 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Salinas Drive, Cebu IT Park',
                'latitude' => '10.3231',
                'longitude' => '123.9062',
                'is_featured' => true,
                'agent_id' => $agents[5]->id,
                'published_at' => now()->subDays(11),
            ],
            [
                'title' => 'Modern 2BR Loft in Lahug',
                'description' => 'Stylish loft-style condominium with high ceilings and modern design. Perfect for creative professionals. Features open floor plan, large windows, and contemporary finishes.',
                'type' => 'Apartment / Condo',
                'price' => 32000,
                'price_type' => 'Monthly',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'garage' => 1,
                'area' => 75,
                'lot_area' => 75,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Swimming Pool', 'Gym', 'Rooftop', 'Security', 'Elevator'],
                'furnishing' => 'Fully Furnished',
                'image' => 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Gorordo Avenue, Lahug',
                'latitude' => '10.3300',
                'longitude' => '123.9000',
                'is_featured' => false,
                'agent_id' => $agents[6]->id,
                'published_at' => now()->subDays(12),
            ],
            [
                'title' => 'Warehouse Space in Mandaue',
                'description' => 'Large warehouse space suitable for storage, distribution, or light manufacturing. Features high ceilings, loading docks, and ample parking. Located in an industrial zone near Cebu City.',
                'type' => 'Warehouse',
                'price' => 65000,
                'price_type' => 'Monthly',
                'bedrooms' => 0,
                'bathrooms' => 2,
                'garage' => 10,
                'area' => 500,
                'lot_area' => 800,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Loading Docks', 'Parking', 'Security', 'High Ceilings'],
                'furnishing' => 'Unfurnished',
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'A.S. Fortuna Street, Mandaue',
                'latitude' => '10.3500',
                'longitude' => '123.9300',
                'is_featured' => false,
                'agent_id' => $agents[6]->id,
                'published_at' => now()->subDays(13),
            ],
            [
                'title' => 'Cozy 1BR Studio near Fuente Circle',
                'description' => 'Affordable studio unit perfect for students or young professionals. Clean, well-maintained, and located near universities. Walking distance to public transport.',
                'type' => 'Studio',
                'price' => 12000,
                'price_type' => 'Monthly',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'garage' => 0,
                'area' => 25,
                'lot_area' => 25,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Security', 'Elevator'],
                'furnishing' => 'Semi Furnished',
                'image' => 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Fuente Osmeña Circle, Cebu City',
                'latitude' => '10.3100',
                'longitude' => '123.8900',
                'is_featured' => false,
                'agent_id' => $agents[7]->id,
                'published_at' => now()->subDays(14),
            ],
            [
                'title' => 'Luxury 3BR Penthouse in Cebu Business Park',
                'description' => 'Exclusive penthouse with panoramic city views, private terrace, and premium finishes. Features high-end appliances, smart home technology, and access to luxury amenities.',
                'type' => 'Apartment / Condo',
                'price' => 95000,
                'price_type' => 'Monthly',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'garage' => 3,
                'area' => 180,
                'lot_area' => 180,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Swimming Pool', 'Gym', 'Rooftop Lounge', 'Concierge', 'Valet Parking', 'Security', 'Private Terrace', 'Smart Home'],
                'furnishing' => 'Fully Furnished',
                'image' => 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Cardinal Rosales Avenue, Cebu Business Park',
                'latitude' => '10.3157',
                'longitude' => '123.8854',
                'is_featured' => true,
                'agent_id' => $agents[7]->id,
                'published_at' => now()->subDays(15),
            ],
            [
                'title' => 'Family 4BR House in Banilad',
                'description' => 'Spacious family home in a quiet subdivision. Features large garden, covered parking, and is close to schools and shopping centers. Perfect for growing families.',
                'type' => 'House',
                'price' => 55000,
                'price_type' => 'Monthly',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'garage' => 2,
                'area' => 220,
                'lot_area' => 350,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Garden', 'Parking', 'Security', 'Maid\'s Room'],
                'furnishing' => 'Semi Furnished',
                'image' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Banilad Road, Banilad',
                'latitude' => '10.3392',
                'longitude' => '123.8944',
                'is_featured' => false,
                'agent_id' => $agents[8]->id,
                'published_at' => now()->subDays(16),
            ],
            [
                'title' => 'Restaurant Space in Ayala Center',
                'description' => 'Prime restaurant space in a high-traffic commercial area. Features kitchen facilities, dining area, and outdoor seating. Perfect for established restaurant chains or new ventures.',
                'type' => 'Commercial',
                'price' => 60000,
                'price_type' => 'Monthly',
                'bedrooms' => 0,
                'bathrooms' => 3,
                'garage' => 8,
                'area' => 180,
                'lot_area' => 180,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Kitchen Facilities', 'Outdoor Seating', 'Parking', 'Security', 'Air Conditioning'],
                'furnishing' => 'Semi Furnished',
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Cardinal Rosales Avenue, Cebu Business Park',
                'latitude' => '10.3157',
                'longitude' => '123.8854',
                'is_featured' => true,
                'agent_id' => $agents[8]->id,
                'published_at' => now()->subDays(17),
            ],
            [
                'title' => 'Modern 2BR Apartment in IT Park',
                'description' => 'Contemporary 2-bedroom apartment with modern amenities. Located in a well-maintained building with 24/7 security. Close to shopping malls and business districts.',
                'type' => 'Apartment / Condo',
                'price' => 24000,
                'price_type' => 'Monthly',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'garage' => 1,
                'area' => 60,
                'lot_area' => 60,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Security', 'Elevator', 'Gym'],
                'furnishing' => 'Fully Furnished',
                'image' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Salinas Drive, Cebu IT Park',
                'latitude' => '10.3231',
                'longitude' => '123.9062',
                'is_featured' => false,
                'agent_id' => $agents[0]->id,
                'published_at' => now()->subDays(18),
            ],
            [
                'title' => 'Luxury 3BR House in Capitol Site',
                'description' => 'Stunning 3-bedroom house with modern design and beautiful garden. Features spacious interiors, private parking, and excellent security. Perfect for families seeking comfort and luxury.',
                'type' => 'House',
                'price' => 60000,
                'price_type' => 'Monthly',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'garage' => 2,
                'area' => 200,
                'lot_area' => 350,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Garden', 'Parking', 'Security', 'Maid\'s Room'],
                'furnishing' => 'Fully Furnished',
                'image' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Escario Street, Capitol Site',
                'latitude' => '10.3100',
                'longitude' => '123.8900',
                'is_featured' => true,
                'agent_id' => $agents[1]->id,
                'published_at' => now()->subDays(19),
            ],
            [
                'title' => 'Co-Working Space in IT Park',
                'description' => 'Modern co-working space with private offices, meeting rooms, and shared workspaces. Features high-speed internet, printing facilities, and kitchen area. Perfect for startups and freelancers.',
                'type' => 'Office',
                'price' => 45000,
                'price_type' => 'Monthly',
                'bedrooms' => 0,
                'bathrooms' => 4,
                'garage' => 6,
                'area' => 250,
                'lot_area' => 250,
                'floor_area_unit' => 'Square Meters',
                'amenities' => ['Meeting Rooms', 'High-Speed Internet', 'Kitchen', 'Parking', 'Security', 'Printing Facilities'],
                'furnishing' => 'Fully Furnished',
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
                'country' => 'Philippines',
                'state_province' => 'Cebu',
                'city' => 'Cebu City',
                'street_address' => 'Pope John Paul II Avenue, Cebu IT Park',
                'latitude' => '10.3200',
                'longitude' => '123.9050',
                'is_featured' => false,
                'agent_id' => $agents[2]->id,
                'published_at' => now()->subDays(20),
            ],
        ];

        // Create properties and ensure all have agent_id assigned
        foreach ($properties as $property) {
            // Ensure agent_id is set - if not, assign to first agent as fallback
            if (!isset($property['agent_id']) || !$property['agent_id']) {
                $property['agent_id'] = $agents[0]->id;
            }
            Property::create($property);
        }

        // Update any existing properties that don't have agent_id assigned
        // Distribute them evenly across all agents
        $propertiesWithoutAgent = Property::whereNull('agent_id')->get();
        if ($propertiesWithoutAgent->count() > 0 && count($agents) > 0) {
            $agentIndex = 0;
            foreach ($propertiesWithoutAgent as $property) {
                $property->agent_id = $agents[$agentIndex % count($agents)]->id;
                $property->save();
                $agentIndex++;
            }
        }

        // Testimonials - 10 total
        $testimonials = [
            [
                'name' => 'Elaine Mae Ofiaza',
                'role' => 'Lessee', 
                'content' => 'Rentals.ph made finding my perfect home so easy! The platform is user-friendly and the properties are all verified. Highly recommended!',
                'avatar' => 'https://i.pravatar.cc/150?img=1',
            ],
            [
                'name' => 'Rica Grate',
                'role' => 'Rent Manager',
                'content' => 'As a rent manager, Rentals.ph has been instrumental in helping me connect with quality tenants. The platform is professional and efficient.',
                'avatar' => 'https://i.pravatar.cc/150?img=2',
            ],
            [
                'name' => 'John Dela Cruz',
                'role' => 'Lessee',
                'content' => 'Found my dream apartment in just a week! The search filters are excellent and the customer service is top-notch.',
                'avatar' => 'https://i.pravatar.cc/150?img=3',
            ],
            [
                'name' => 'Maria Santos',
                'role' => 'Property Owner',
                'content' => 'Listing my property was straightforward and I got quality inquiries within days. Great platform!',
                'avatar' => 'https://i.pravatar.cc/150?img=4',
            ],
            [
                'name' => 'Carlos Rodriguez',
                'role' => 'Lessee',
                'content' => 'The verification process gives me confidence. I know all properties are legitimate and well-maintained.',
                'avatar' => 'https://i.pravatar.cc/150?img=5',
            ],
            [
                'name' => 'Grandy & Fave',
                'role' => 'Rent Manager',
                'content' => 'Rent.ph has been an invaluable asset in our rental management journey. This platform has simplified and streamlined our operations, allowing us to effectively manage our rental properties with ease.',
                'avatar' => 'https://i.pravatar.cc/150?img=6',
            ],
            [
                'name' => 'Sarah Johnson',
                'role' => 'Lessee',
                'content' => 'Moving to Manila was made so much easier thanks to Rentals.ph. Found a great place in BGC within my budget!',
                'avatar' => 'https://i.pravatar.cc/150?img=7',
            ],
            [
                'name' => 'Michael Chen',
                'role' => 'Property Owner',
                'content' => 'As a property owner, I appreciate how Rentals.ph helps me find reliable tenants quickly. The platform is well-designed and user-friendly.',
                'avatar' => 'https://i.pravatar.cc/150?img=8',
            ],
            [
                'name' => 'Ana Garcia',
                'role' => 'Lessee',
                'content' => 'The detailed property listings with photos and descriptions helped me make an informed decision. Very satisfied with my rental!',
                'avatar' => 'https://i.pravatar.cc/150?img=9',
            ],
            [
                'name' => 'Robert Tan',
                'role' => 'Rent Manager',
                'content' => 'Excellent platform for managing multiple properties. The dashboard is intuitive and the support team is always helpful.',
                'avatar' => 'https://i.pravatar.cc/150?img=10',
            ],
            [
                'name' => 'Patricia Lee',
                'role' => 'Lessee',
                'content' => 'I\'ve been using Rentals.ph for over a year now and it\'s been amazing. The property listings are detailed and accurate, and I found my perfect home quickly.',
                'avatar' => 'https://i.pravatar.cc/150?img=11',
            ],
            [
                'name' => 'Mark Villanueva',
                'role' => 'Property Owner',
                'content' => 'As a property owner, Rentals.ph has made it so easy to find quality tenants. The verification process gives me peace of mind.',
                'avatar' => 'https://i.pravatar.cc/150?img=12',
            ],
            [
                'name' => 'Jennifer Lopez',
                'role' => 'Lessee',
                'content' => 'Moving to a new city was stressful, but Rentals.ph made finding a place so much easier. The search filters are excellent and saved me so much time!',
                'avatar' => 'https://i.pravatar.cc/150?img=13',
            ],
            [
                'name' => 'Francisco Ramos',
                'role' => 'Rent Manager',
                'content' => 'Managing properties has never been easier. The platform handles everything from listings to inquiries, allowing me to focus on what matters most.',
                'avatar' => 'https://i.pravatar.cc/150?img=14',
            ],
            [
                'name' => 'Lisa Wong',
                'role' => 'Lessee',
                'content' => 'The customer service team is incredibly responsive and helpful. They answered all my questions and helped me through the entire rental process.',
                'avatar' => 'https://i.pravatar.cc/150?img=15',
            ],
            [
                'name' => 'Daniel Kim',
                'role' => 'Property Owner',
                'content' => 'I\'ve listed multiple properties on Rentals.ph and the response has been fantastic. The platform attracts serious, qualified tenants.',
                'avatar' => 'https://i.pravatar.cc/150?img=16',
            ],
            [
                'name' => 'Amanda Torres',
                'role' => 'Lessee',
                'content' => 'The property photos and virtual tours on Rentals.ph are excellent. I knew exactly what to expect before even visiting the property.',
                'avatar' => 'https://i.pravatar.cc/150?img=17',
            ],
            [
                'name' => 'Ricardo Mendoza',
                'role' => 'Rent Manager',
                'content' => 'The analytics and reporting features help me understand my property performance better. It\'s a game-changer for property management.',
                'avatar' => 'https://i.pravatar.cc/150?img=18',
            ],
            [
                'name' => 'Sophia Chen',
                'role' => 'Lessee',
                'content' => 'I love how user-friendly the platform is. Even as a first-time renter, I found it easy to navigate and find exactly what I was looking for.',
                'avatar' => 'https://i.pravatar.cc/150?img=19',
            ],
            [
                'name' => 'Eduardo Santos',
                'role' => 'Property Owner',
                'content' => 'Rentals.ph has streamlined my rental business. The automated features save me hours of work every week.',
                'avatar' => 'https://i.pravatar.cc/150?img=20',
            ],
            [
                'name' => 'Michelle Rivera',
                'role' => 'Lessee',
                'content' => 'The verification badges on properties give me confidence that I\'m dealing with legitimate listings. No more worrying about scams!',
                'avatar' => 'https://i.pravatar.cc/150?img=21',
            ],
            [
                'name' => 'Antonio Cruz',
                'role' => 'Rent Manager',
                'content' => 'The mobile app is fantastic! I can manage my properties and respond to inquiries even when I\'m on the go.',
                'avatar' => 'https://i.pravatar.cc/150?img=22',
            ],
            [
                'name' => 'Grace Lim',
                'role' => 'Lessee',
                'content' => 'Found my dream apartment in BGC through Rentals.ph. The process was smooth from start to finish, and I couldn\'t be happier!',
                'avatar' => 'https://i.pravatar.cc/150?img=23',
            ],
            [
                'name' => 'Jose Martinez',
                'role' => 'Property Owner',
                'content' => 'The platform\'s marketing tools help my properties get maximum visibility. I\'ve seen a significant increase in inquiries since joining.',
                'avatar' => 'https://i.pravatar.cc/150?img=24',
            ],
        ];

        foreach ($testimonials as $testimonial) {
            Testimonial::create($testimonial);
        }

        // Blog Posts
        $blogs = [
            [
                'title' => 'Understanding Your Rental Contract: A Complete Guide',
                'content' => 'Renting a property in the Philippines requires a thorough understanding of rental contracts. This comprehensive guide covers all essential aspects of rental agreements, including key terms, tenant rights, landlord obligations, and what to look for before signing. We\'ll walk you through common clauses, security deposits, lease duration, and renewal options. Understanding these elements will help you make informed decisions and protect your interests as a tenant.',
                'excerpt' => 'Learn everything you need to know about rental contracts in the Philippines, including key terms, rights, and obligations.',
                'category' => 'Legal',
                'read_time' => 7,
                'likes' => 342,
                'comments' => 24,
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
                'published_at' => now()->subDays(10),
            ],
            [
                'title' => 'Top 10 Neighborhoods to Rent in Metro Manila',
                'content' => 'Metro Manila offers diverse neighborhoods, each with unique characteristics and advantages. From the bustling business districts of Makati and BGC to the cultural hubs of Quezon City and the emerging areas of Pasig and Mandaluyong, we explore the top 10 neighborhoods for renters. This guide covers affordability, accessibility, safety, amenities, and lifestyle factors to help you find the perfect location that matches your needs and budget.',
                'excerpt' => 'Discover the best neighborhoods in Metro Manila for renting, from business districts to residential communities.',
                'category' => 'Location Guide',
                'read_time' => 10,
                'likes' => 289,
                'comments' => 18,
                'author' => 'John Dela Cruz',
                'image' => 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800',
                'published_at' => now()->subDays(8),
            ],
            [
                'title' => 'First-Time Renter\'s Checklist: What You Need to Know',
                'content' => 'Renting your first property can be overwhelming. This checklist covers everything from budgeting and finding the right property to understanding lease terms and moving in. We\'ll help you navigate the rental process step by step, including how to prepare your documents, what questions to ask landlords, how to inspect a property, and tips for negotiating terms. Make your first rental experience smooth and stress-free with our comprehensive guide.',
                'excerpt' => 'A complete checklist for first-time renters covering everything from budgeting to moving in.',
                'category' => 'Tips & Advice',
                'read_time' => 8,
                'likes' => 156,
                'comments' => 12,
                'author' => 'Sarah Garcia',
                'image' => 'https://images.unsplash.com/photo-1556912172-45b7abe8b7c1?w=800',
                'published_at' => now()->subDays(6),
            ],
            [
                'title' => 'How to Negotiate Your Rent: Expert Tips',
                'content' => 'Rent negotiation is an art that can save you significant money over time. Learn proven strategies for negotiating rent, including when to negotiate, how to present your case, and what leverage points to use. We cover market research, timing, long-term lease benefits, and how to maintain good relationships with landlords while getting the best deal. These expert tips can help you secure favorable rental terms.',
                'excerpt' => 'Master the art of rent negotiation with expert tips and strategies to get the best deal.',
                'category' => 'Tips & Advice',
                'read_time' => 6,
                'likes' => 203,
                'comments' => 15,
                'author' => 'Michael Reyes',
                'image' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800',
                'published_at' => now()->subDays(5),
            ],
            [
                'title' => 'Rental Property Inspection: What to Look For',
                'content' => 'A thorough property inspection is crucial before signing a lease. This guide covers essential areas to check, including structural integrity, plumbing, electrical systems, appliances, security features, and potential maintenance issues. We provide a detailed inspection checklist and explain how to document findings, negotiate repairs, and protect yourself from future disputes. Don\'t skip this important step in the rental process.',
                'excerpt' => 'Learn what to inspect before renting a property and how to identify potential issues.',
                'category' => 'Tips & Advice',
                'read_time' => 9,
                'likes' => 178,
                'comments' => 9,
                'author' => 'Anna Martinez',
                'image' => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
                'published_at' => now()->subDays(4),
            ],
            [
                'title' => 'Understanding Security Deposits in the Philippines',
                'content' => 'Security deposits are a standard part of renting, but many tenants don\'t fully understand how they work. This article explains security deposit regulations in the Philippines, including legal limits, when deposits can be withheld, how to get your deposit back, and what to do in case of disputes. We also cover advance payments, utility deposits, and best practices for protecting your deposit throughout your tenancy.',
                'excerpt' => 'Everything you need to know about security deposits, including regulations and how to protect your money.',
                'category' => 'Legal',
                'read_time' => 7,
                'likes' => 267,
                'comments' => 21,
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Furnished vs. Unfurnished: Which is Right for You?',
                'content' => 'Choosing between furnished and unfurnished rentals is a significant decision that affects both your budget and lifestyle. We compare the pros and cons of each option, including cost considerations, flexibility, maintenance responsibilities, and personal preferences. This guide helps you evaluate your situation and make the best choice based on your needs, budget, and how long you plan to stay.',
                'excerpt' => 'Compare furnished and unfurnished rentals to determine which option best suits your needs and budget.',
                'category' => 'Tips & Advice',
                'read_time' => 6,
                'likes' => 134,
                'comments' => 8,
                'author' => 'Robert Tan',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Renting Commercial Spaces: A Business Owner\'s Guide',
                'content' => 'Renting commercial space requires different considerations than residential rentals. This guide covers location analysis, lease terms specific to commercial properties, zoning requirements, build-out costs, and negotiation strategies. We explore different types of commercial spaces, from retail stores to offices, and provide insights on what business owners need to know before signing a commercial lease in the Philippines.',
                'excerpt' => 'Essential information for business owners looking to rent commercial spaces in the Philippines.',
                'category' => 'Commercial',
                'read_time' => 11,
                'likes' => 198,
                'comments' => 16,
                'author' => 'Jennifer Lim',
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'Pet-Friendly Rentals: Finding the Right Place',
                'content' => 'Finding a pet-friendly rental can be challenging, but it\'s not impossible. This article covers how to search for pet-friendly properties, what landlords typically look for, pet deposits and fees, and how to present yourself and your pet as responsible tenants. We also discuss pet policies, breed restrictions, and tips for maintaining a good relationship with your landlord while keeping your furry friend.',
                'excerpt' => 'Tips and strategies for finding and securing pet-friendly rental properties.',
                'category' => 'Tips & Advice',
                'read_time' => 5,
                'likes' => 112,
                'comments' => 7,
                'author' => 'Lisa Chen',
                'image' => 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800',
                'published_at' => now()->subDays(0),
            ],
            [
                'title' => 'Rental Scams: How to Protect Yourself',
                'content' => 'Rental scams are unfortunately common, but you can protect yourself by knowing the warning signs. This article identifies common scam tactics, including fake listings, advance fee fraud, and identity theft schemes. We provide red flags to watch for, verification steps to take, and best practices for safely searching for rentals online. Learn how to spot scams and protect your money and personal information.',
                'excerpt' => 'Learn to identify and avoid common rental scams with our comprehensive protection guide.',
                'category' => 'Safety',
                'read_time' => 8,
                'likes' => 445,
                'comments' => 32,
                'author' => 'David Ong',
                'image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
                'published_at' => now()->subHours(12),
            ],
            [
                'title' => 'Understanding Property Taxes for Renters and Landlords',
                'content' => 'Property taxes can be confusing for both renters and landlords. This comprehensive guide explains how property taxes work in the Philippines, who is responsible for paying them, how they\'re calculated, and what deductions or exemptions may apply. We also cover tax implications for rental income and provide tips for staying compliant with tax regulations.',
                'excerpt' => 'A complete guide to property taxes for renters and landlords in the Philippines.',
                'category' => 'Legal',
                'read_time' => 9,
                'likes' => 198,
                'comments' => 14,
                'author' => 'Carlos Rodriguez',
                'image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
                'published_at' => now()->subHours(6),
            ],
            [
                'title' => 'Moving Day Checklist: Don\'t Forget These Essentials',
                'content' => 'Moving to a new rental property can be overwhelming, but a good checklist makes all the difference. This article covers everything you need to do before, during, and after your move, including utility transfers, change of address notifications, packing tips, and what to do on moving day itself. Follow this checklist for a smooth, stress-free move.',
                'excerpt' => 'A comprehensive moving day checklist to ensure nothing is forgotten.',
                'category' => 'Tips & Advice',
                'read_time' => 7,
                'likes' => 167,
                'comments' => 11,
                'author' => 'Patricia Lee',
                'image' => 'https://images.unsplash.com/photo-1556912172-45b7abe8b7c1?w=800',
                'published_at' => now()->subHours(3),
            ],
            [
                'title' => 'Sustainable Living: Eco-Friendly Rental Properties',
                'content' => 'More renters are looking for eco-friendly properties that align with their values. This guide explores sustainable features to look for in rental properties, including energy-efficient appliances, solar panels, water-saving fixtures, and green building materials. We also discuss how sustainability can save you money and reduce your environmental footprint.',
                'excerpt' => 'Discover how to find and live in eco-friendly rental properties.',
                'category' => 'Lifestyle',
                'read_time' => 8,
                'likes' => 223,
                'comments' => 19,
                'author' => 'Elena Martinez',
                'image' => 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800',
                'published_at' => now()->subHours(1),
            ],
            [
                'title' => 'Rental Market Trends: What to Expect in 2024',
                'content' => 'Stay ahead of the curve with our analysis of rental market trends for 2024. We examine price trends, popular neighborhoods, emerging areas, and factors affecting the rental market. Whether you\'re a renter or landlord, understanding these trends can help you make informed decisions about your rental property needs.',
                'excerpt' => 'An in-depth look at rental market trends and what to expect in the coming year.',
                'category' => 'Market Analysis',
                'read_time' => 10,
                'likes' => 312,
                'comments' => 28,
                'author' => 'Michael Chen',
                'image' => 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800',
                'published_at' => now()->subDays(1)->subHours(18),
            ],
            [
                'title' => 'Home Staging Tips for Rental Properties',
                'content' => 'Proper staging can make your rental property stand out and attract quality tenants faster. This guide covers essential staging techniques, from decluttering and depersonalizing to furniture arrangement and lighting. Learn how to showcase your property\'s best features and create an inviting atmosphere that helps potential tenants envision themselves living there.',
                'excerpt' => 'Expert tips for staging your rental property to attract quality tenants.',
                'category' => 'Tips & Advice',
                'read_time' => 6,
                'likes' => 145,
                'comments' => 10,
                'author' => 'Sarah Johnson',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'published_at' => now()->subDays(1)->subHours(12),
            ],
            [
                'title' => 'Renter\'s Insurance: What You Need to Know',
                'content' => 'Many renters overlook the importance of renter\'s insurance, but it can protect your belongings and provide liability coverage. This article explains what renter\'s insurance covers, how much it typically costs, what to look for in a policy, and why it\'s essential even if your landlord has property insurance. Don\'t leave your belongings unprotected.',
                'excerpt' => 'Everything you need to know about renter\'s insurance and why you need it.',
                'category' => 'Safety',
                'read_time' => 7,
                'likes' => 189,
                'comments' => 13,
                'author' => 'David Ong',
                'image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
                'published_at' => now()->subDays(1)->subHours(6),
            ],
            [
                'title' => 'Short-Term vs. Long-Term Rentals: Making the Right Choice',
                'content' => 'Choosing between short-term and long-term rentals depends on your goals, lifestyle, and financial situation. This comprehensive comparison covers the pros and cons of each option, including cost considerations, flexibility, legal requirements, and market demand. Whether you\'re a property owner or renter, this guide helps you make the best decision.',
                'excerpt' => 'Compare short-term and long-term rental options to find what works best for you.',
                'category' => 'Tips & Advice',
                'read_time' => 9,
                'likes' => 256,
                'comments' => 22,
                'author' => 'Jennifer Lim',
                'image' => 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Building Credit Through Rental Payments',
                'content' => 'Did you know that your rental payments can help build your credit? This article explains how to report rental payments to credit bureaus, the benefits of building credit through rent, and alternative methods for establishing credit history. Learn how responsible renting can improve your financial profile and open doors to better opportunities.',
                'excerpt' => 'Discover how rental payments can help you build and improve your credit score.',
                'category' => 'Financial',
                'read_time' => 6,
                'likes' => 178,
                'comments' => 15,
                'author' => 'Robert Tan',
                'image' => 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800',
                'published_at' => now()->subDays(2)->subHours(12),
            ],
            [
                'title' => 'Accessibility Features in Rental Properties',
                'content' => 'Finding accessible rental properties is crucial for individuals with disabilities or mobility challenges. This guide covers important accessibility features to look for, including wheelchair accessibility, grab bars, wide doorways, and accessible parking. We also discuss your rights as a tenant with disabilities and how to request reasonable accommodations.',
                'excerpt' => 'A guide to finding accessible rental properties and understanding your rights.',
                'category' => 'Lifestyle',
                'read_time' => 7,
                'likes' => 134,
                'comments' => 9,
                'author' => 'Anna Martinez',
                'image' => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Rental Property Photography: Tips for Great Listings',
                'content' => 'High-quality photos are essential for attracting tenants to your rental property. This guide covers professional photography tips, including lighting, angles, staging, and editing. Learn how to showcase your property\'s best features, avoid common photography mistakes, and create listings that stand out from the competition.',
                'excerpt' => 'Professional tips for taking great photos of your rental property.',
                'category' => 'Tips & Advice',
                'read_time' => 5,
                'likes' => 167,
                'comments' => 12,
                'author' => 'Mark Villanueva',
                'image' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
                'published_at' => now()->subDays(3)->subHours(12),
            ],
            [
                'title' => 'Understanding Lease Renewal Options',
                'content' => 'When your lease is about to expire, you have several options to consider. This article explains lease renewal processes, month-to-month options, early termination clauses, and how to negotiate renewal terms. We also cover what happens if you want to stay but your landlord doesn\'t renew, and your rights as a tenant.',
                'excerpt' => 'Navigate lease renewal options and understand your rights as a tenant.',
                'category' => 'Legal',
                'read_time' => 8,
                'likes' => 201,
                'comments' => 16,
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800',
                'published_at' => now()->subDays(4),
            ],
            [
                'title' => 'Smart Home Features for Rental Properties',
                'content' => 'Smart home technology is becoming increasingly popular in rental properties. This guide explores smart home features that can enhance your rental experience, including smart locks, thermostats, lighting, and security systems. We discuss benefits for both landlords and tenants, installation considerations, and privacy concerns.',
                'excerpt' => 'Explore smart home features that can enhance your rental property experience.',
                'category' => 'Technology',
                'read_time' => 7,
                'likes' => 234,
                'comments' => 20,
                'author' => 'Ana Garcia',
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
                'published_at' => now()->subDays(4)->subHours(12),
            ],
            [
                'title' => 'Rental Property Maintenance: A Landlord\'s Guide',
                'content' => 'Proper maintenance is key to protecting your investment and keeping tenants happy. This comprehensive guide covers preventive maintenance schedules, common repair issues, when to call professionals, and how to handle maintenance requests. Learn how to maintain your property efficiently while minimizing costs and maximizing tenant satisfaction.',
                'excerpt' => 'Essential maintenance tips for landlords to protect their investment.',
                'category' => 'Tips & Advice',
                'read_time' => 10,
                'likes' => 278,
                'comments' => 24,
                'author' => 'James Wilson',
                'image' => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
                'published_at' => now()->subDays(5),
            ],
        ];

        foreach ($blogs as $blog) {
            Blog::create($blog);
        }

        // News Articles - 10 total
        $news = [
            [
                'title' => 'Scientist Discover Promising New Treatment for Disease',
                'content' => 'Researchers have announced a breakthrough in medical science, identifying a novel treatment that shows significant promise in combating a widespread disease. Early trials indicate high efficacy and minimal side effects, offering hope for millions worldwide.',
                'excerpt' => 'A new medical treatment has been discovered, showing promising results in early trials.',
                'category' => 'Science',
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1532187863566-d11110711101?w=800',
                'published_at' => now()->subDays(15),
            ],
            [
                'title' => 'New Economic Policies Show Positive Impact on Local Markets',
                'content' => 'The government\'s recently implemented economic policies are beginning to yield positive results, with local markets experiencing a surge in activity. Analysts predict sustained growth and increased consumer confidence in the coming months.',
                'excerpt' => 'Economic policies are boosting local markets, with predictions of sustained growth.',
                'category' => 'Economy',
                'author' => 'John Reyes',
                'image' => 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800',
                'published_at' => now()->subDays(14),
            ],
            [
                'title' => 'Tech Innovation Drives Real Estate Market Growth',
                'content' => 'Technological advancements are revolutionizing the real estate sector, leading to unprecedented growth. New platforms and tools are streamlining property management, sales, and rentals, making the market more efficient and accessible.',
                'excerpt' => 'Technology is transforming real estate, making it more efficient and accessible.',
                'category' => 'Technology',
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                'published_at' => now()->subDays(13),
            ],
            [
                'title' => 'Government Announces New Housing Development Plans',
                'content' => 'In a bid to address housing shortages, the government has unveiled ambitious new housing development plans. The initiative aims to provide affordable and sustainable living options for a wider population, with projects slated across key urban areas.',
                'excerpt' => 'New government plans aim to tackle housing shortages with affordable projects.',
                'category' => 'Politics',
                'author' => 'Ana Garcia',
                'image' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'published_at' => now()->subDays(12),
            ],
            [
                'title' => 'Healthcare Facilities Expand Across Metro Manila',
                'content' => 'Several new healthcare facilities and expansions of existing ones have been announced for Metro Manila. This development is expected to significantly improve access to medical services and enhance public health infrastructure in the region.',
                'excerpt' => 'Metro Manila\'s healthcare infrastructure is expanding with new facilities.',
                'category' => 'Health',
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1532187863566-d11110711101?w=800',
                'published_at' => now()->subDays(11),
            ],
            [
                'title' => 'Popular Tourist Destination Implements New Entry Rules',
                'content' => 'A renowned tourist destination has introduced new entry regulations to promote sustainable tourism and protect its natural resources. Visitors are advised to check the updated guidelines before planning their trips.',
                'excerpt' => 'New entry rules are in effect at a popular tourist spot for sustainable tourism.',
                'category' => 'Politics',
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'published_at' => now()->subDays(10),
            ],
            [
                'title' => 'Local Community Rallies to Support Flood Victims',
                'content' => 'Following recent heavy rains and flooding, local communities have come together to provide aid and support to affected residents. Relief efforts are underway, with volunteers distributing food, water, and essential supplies.',
                'excerpt' => 'Communities unite to aid flood victims with relief efforts and supplies.',
                'category' => 'Politics',
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                'published_at' => now()->subDays(9),
            ],
            [
                'title' => 'Wildlife Conservation Efforts Show Positive Results',
                'content' => 'Ongoing wildlife conservation programs are reporting significant successes, with several endangered species showing signs of recovery. These efforts highlight the importance of environmental protection and biodiversity.',
                'excerpt' => 'Conservation programs are successfully aiding endangered species recovery.',
                'category' => 'Science',
                'author' => 'John Reyes',
                'image' => 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800',
                'published_at' => now()->subDays(8),
            ],
            [
                'title' => 'New AI Tools Transform Property Management',
                'content' => 'Artificial intelligence is set to revolutionize property management, with new AI-powered tools offering automated solutions for tenant communication, maintenance scheduling, and predictive analytics. This innovation promises greater efficiency and cost savings.',
                'excerpt' => 'AI tools are set to transform property management with automated solutions.',
                'category' => 'Technology',
                'author' => 'Ana Garcia',
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
                'published_at' => now()->subDays(7),
            ],
            [
                'title' => 'City Council Approves New Zoning Regulations',
                'content' => 'The City Council has approved a new set of zoning regulations aimed at promoting urban development and ensuring sustainable land use. These changes will impact future construction projects and property values within the city.',
                'excerpt' => 'New zoning regulations approved by City Council will impact urban development.',
                'category' => 'Politics',
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'published_at' => now()->subDays(6),
            ],
            [
                'title' => 'Metro Manila Rental Prices See Steady Growth in Q1',
                'content' => 'Metro Manila\'s rental market has shown steady growth in the first quarter, with average rental prices increasing by 8% compared to the previous quarter. Analysts attribute this growth to increased demand from returning expatriates and local professionals relocating to the capital. The trend is expected to continue throughout the year.',
                'excerpt' => 'Rental prices in Metro Manila increased by 8% in Q1, driven by strong demand.',
                'category' => 'Economy',
                'author' => 'John Reyes',
                'image' => 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800',
                'published_at' => now()->subDays(5),
            ],
            [
                'title' => 'New MRT Line Extension to Boost Property Values',
                'content' => 'The recently announced MRT line extension project is expected to significantly boost property values in surrounding areas. Real estate experts predict a 15-20% increase in property values near new stations, making these areas attractive for both investors and renters seeking convenient transportation access.',
                'excerpt' => 'MRT extension project expected to increase nearby property values by 15-20%.',
                'category' => 'Politics',
                'author' => 'Ana Garcia',
                'image' => 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800',
                'published_at' => now()->subDays(4),
            ],
            [
                'title' => 'Digital Nomad Visas Attract International Renters',
                'content' => 'The Philippines\' new digital nomad visa program is attracting international remote workers, creating increased demand for short-term and furnished rentals. Property managers report a 30% increase in inquiries from foreign professionals seeking rental accommodations in Metro Manila and popular tourist destinations.',
                'excerpt' => 'Digital nomad visa program driving increased rental demand from international workers.',
                'category' => 'Politics',
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Green Building Certification Gains Traction in Rental Market',
                'content' => 'More property developers are seeking green building certifications as renters increasingly prioritize sustainability. Properties with LEED or BERDE certifications are commanding premium rental rates and experiencing faster occupancy rates, signaling a shift toward environmentally conscious rental choices.',
                'excerpt' => 'Green building certifications becoming a key factor in rental property selection.',
                'category' => 'Technology',
                'author' => 'John Reyes',
                'image' => 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'BGC Named Top Rental Destination for Young Professionals',
                'content' => 'Bonifacio Global City has been ranked as the top rental destination for young professionals in Metro Manila. The area\'s modern infrastructure, vibrant lifestyle, and proximity to business districts make it highly attractive to millennials and Gen Z renters seeking work-life balance.',
                'excerpt' => 'BGC tops the list as the most popular rental destination for young professionals.',
                'category' => 'Lifestyle',
                'author' => 'Ana Garcia',
                'image' => 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'Property Technology Startups Raise Record Funding',
                'content' => 'Property technology startups in the Philippines have raised a record $50 million in funding this quarter, signaling strong investor confidence in the sector. These startups are developing innovative solutions for property management, virtual tours, and rental marketplaces.',
                'excerpt' => 'PropTech startups raise $50M in record-breaking funding quarter.',
                'category' => 'Technology',
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
                'published_at' => now()->subHours(20),
            ],
            [
                'title' => 'New Rent Control Measures Take Effect',
                'content' => 'New rent control measures have taken effect, providing additional protections for tenants while ensuring fair returns for property owners. The regulations cap annual rent increases and establish clearer guidelines for lease renewals and eviction procedures.',
                'excerpt' => 'New rent control measures provide enhanced tenant protections.',
                'category' => 'Politics',
                'author' => 'John Reyes',
                'image' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'published_at' => now()->subHours(16),
            ],
            [
                'title' => 'Co-Living Spaces Gain Popularity Among Millennials',
                'content' => 'Co-living spaces are gaining popularity among millennials and young professionals in Metro Manila. These shared living arrangements offer affordable housing options with built-in community and amenities, addressing the housing needs of urban professionals seeking flexible, social living environments.',
                'excerpt' => 'Co-living spaces becoming popular choice for millennials seeking affordable urban living.',
                'category' => 'Lifestyle',
                'author' => 'Ana Garcia',
                'image' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                'published_at' => now()->subHours(12),
            ],
            [
                'title' => 'Virtual Reality Property Tours Transform Rental Market',
                'content' => 'Virtual reality property tours are revolutionizing the rental market, allowing potential tenants to explore properties remotely. This technology has become especially popular among international renters and busy professionals, reducing the need for physical property visits and speeding up the rental decision process.',
                'excerpt' => 'VR property tours are changing how renters explore and choose properties.',
                'category' => 'Technology',
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                'published_at' => now()->subHours(8),
            ],
            [
                'title' => 'Affordable Housing Initiative Launches in Quezon City',
                'content' => 'A new affordable housing initiative has launched in Quezon City, aiming to provide quality rental accommodations for low to middle-income families. The project includes 500 units with modern amenities and is part of a broader effort to address housing affordability in Metro Manila.',
                'excerpt' => 'New affordable housing project launches with 500 units in Quezon City.',
                'category' => 'Politics',
                'author' => 'John Reyes',
                'image' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'published_at' => now()->subHours(4),
            ],
            [
                'title' => 'Rental Market Sees Surge in Pet-Friendly Listings',
                'content' => 'The rental market is experiencing a surge in pet-friendly property listings, with landlords recognizing the growing demand from pet owners. Properties that welcome pets are seeing faster occupancy rates and can command slightly higher rents, reflecting the value pet owners place on finding suitable accommodations.',
                'excerpt' => 'Pet-friendly rental listings on the rise as landlords respond to market demand.',
                'category' => 'Lifestyle',
                'author' => 'Ana Garcia',
                'image' => 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800',
                'published_at' => now()->subHours(2),
            ],
            [
                'title' => 'Makati CBD Office Space Demand Reaches New High',
                'content' => 'Demand for office space in Makati Central Business District has reached a new high, with vacancy rates dropping to historic lows. The strong demand is driving up rental rates for both office and residential properties in the area, as businesses and employees seek proximity to the business hub.',
                'excerpt' => 'Makati CBD office space demand hits record high, driving rental rates upward.',
                'category' => 'Economy',
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
                'published_at' => now()->subHours(1),
            ],
            [
                'title' => 'Student Housing Market Expands Near Universities',
                'content' => 'The student housing market is expanding rapidly near major universities in Metro Manila. Property developers are building purpose-built student accommodations with modern amenities, study spaces, and security features, addressing the growing demand from both local and international students.',
                'excerpt' => 'Student housing market growing near universities with purpose-built accommodations.',
                'category' => 'Education',
                'author' => 'John Reyes',
                'image' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                'published_at' => now()->subMinutes(30),
            ],
            [
                'title' => 'Rental Payment Platforms Simplify Transactions',
                'content' => 'New digital payment platforms are simplifying rental transactions for both landlords and tenants. These platforms offer automated rent collection, payment reminders, and transaction records, reducing administrative burden and improving payment reliability. Adoption rates are increasing rapidly across Metro Manila.',
                'excerpt' => 'Digital payment platforms are streamlining rental transactions and improving efficiency.',
                'category' => 'Technology',
                'author' => 'Ana Garcia',
                'image' => 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800',
                'published_at' => now()->subMinutes(15),
            ],
            [
                'title' => 'Luxury Rental Market Shows Strong Performance',
                'content' => 'The luxury rental market in Metro Manila is showing strong performance, with high-end properties experiencing high occupancy rates and premium rental yields. International expatriates, executives, and affluent local professionals are driving demand for luxury accommodations with premium amenities and prime locations.',
                'excerpt' => 'Luxury rental market performing strongly with high occupancy and premium yields.',
                'category' => 'Economy',
                'author' => 'Maria Santos',
                'image' => 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                'published_at' => now(),
            ],
        ];

        foreach ($news as $newsArticle) {
            News::create($newsArticle);
        }
    }
}

